<a href="https://colab.research.google.com/github/rajavi-mhatre/flyrank-ml/blob/main/work/notebooks/w04_baseline_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-07 — Baseline Action Score and Top-20 Review

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*

In [ ]:
!git clone https://github.com/rajavi-mhatre/flyrank-ml.git

fatal: destination path 'flyrank-ml' already exists and is not an empty directory.


In [ ]:
import pandas as pd

df = pd.read_csv("flyrank-ml/data/raw/content_refresh_anonymized.csv")

print(df.head())
print(df.columns.tolist())
# Refresh page if last updated>90 days ago, has low clicks but high impressions.

             content_id          client_id  search_volume  competition  \
0  content_304f48230142  client_f369cb89fc           10.0         0.67   
1  content_a1fb4e703a9e  client_4e07408562           90.0         0.01   
2  content_9aa793d4d895  client_7f2253d7e2            0.0         0.00   
3  content_331d6c4de07b  client_19581e27de           10.0         0.00   
4  content_d99b7a2d90ca  client_3fdba35f04            0.0         0.00   

  competition_level   cpc     content_type    main_intent  word_count  \
0              HIGH  2.05  keyword article  transactional      3221.0   
1               LOW  0.05  keyword article  informational      2481.0   
2               LOW  0.00  keyword article  informational      3515.0   
3               LOW  0.00  keyword article     commercial         NaN   
4               LOW  0.00  keyword article  informational      2803.0   

   char_count  ... char_count_tier   ctr  avg_position  engagement_rate  \
0     20457.0  ...     15000-25000  0.76 

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [ ]:
high_impressions= df["impressions_90d"].median()
lower_ctr=df["ctr"].median()
print("High impressions and low CTR = ", high_impressions," and ", lower_ctr)

a = (df["days_since_last_update"] > 90).astype(int)
b = (df["impressions_90d"] >= high_impressions).astype(int)
c = (df["ctr"] < lower_ctr).astype(int)
df["score"]=a+b+c
print(df[["days_since_last_update","impressions_90d","ctr","score"]].head())

df=df.sort_values("score", ascending=False)
# df.to_csv("work/outputs/baseline_action_score.csv", index=False)

High impressions and low CTR =  731.0  and  0.07
   days_since_last_update  impressions_90d   ctr  score
0                      20             3803  0.76      1
1                      25            15320  0.05      2
2                      20            12581  0.09      1
3                      22            11751  0.49      1
4                      14            19140  0.13      1


## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

In [ ]:
top_20 = df.head(20)
print(top_20[[
    "days_since_last_update",
    "impressions_90d",
    "ctr",
    "score",
    "avg_position"
]])

# #	Page	Action	Reason code	Confidence note	What would make it wrong
# 1	25462	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Strong candidate: 16,786 impressions, 0 CTR, and position 5.6.	CTR could be affected by search intent or another factor rather than freshness.
# 2	10162	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets all three conditions, with 748 impressions and 0 CTR.	Relatively low impressions mean the potential impact may be limited.
# 3	5716	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline, but position 41.2 makes the low CTR less surprising.	Poor ranking may be the main problem rather than outdated content.
# 4	24521	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets all three baseline conditions with 890 impressions and 0 CTR.	Limited impressions may indicate limited search demand.
# 5	1422	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Stronger candidate because it has 9,046 impressions and 0.02 CTR.	Position 33.2 may explain some of the low CTR.
# 6	28482	REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the rule, but position 47.1 makes the low CTR less useful as evidence of a content problem.	Poor ranking may be the main reason for the low CTR.
# 7	12451	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Reasonable candidate with 2,877 impressions and 0 CTR.	Position 22.5 could contribute to the low CTR.
# 8	5759	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	More convincing because position 6.1 is relatively strong while CTR is 0.05.	Search intent could naturally produce low CTR even at a good position.
# 9	18131	REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline, but only has 872 impressions. Its position of 10.8 is relatively strong.	Limited search volume may make a refresh less valuable.
# 10	5729	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Position 8.6 and 0.05 CTR make the low CTR worth investigating.	Search intent could explain the low CTR.
# 11	5732	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Strong candidate because it has position 4.5 and 0 CTR.	Low search volume of 818 impressions may limit potential gains.
# 12	8306	REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline but has position 26.2, which may explain some of the low CTR.	Ranking may be a larger issue than content freshness.
# 13	14771	REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline, but has relatively low impressions and position 26.1.	Limited visibility and ranking may reduce the value of a refresh.
# 14	29629	REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline, although it has only 98 days since update and 890 impressions.	The page is only slightly beyond the staleness threshold and has limited visibility.
# 15	8335	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets all three conditions with 2,179 impressions and 0 CTR.	Position 32.3 may be contributing to the low CTR.
# 16	5740	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Stronger candidate because it has 8,365 impressions, position 11.0, and 0.04 CTR.	Search intent may explain the relatively low CTR.
# 17	18123	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Strong candidate because position 2.9 is good while CTR is 0.	The low CTR may reflect the type of queries generating the impressions.
# 18	4489	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Strong candidate with 10,003 impressions, position 8.6, and 0.06 CTR.	Search intent or features could explain the CTR.
# 19	18118	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline and has 2,152 impressions with position 33.4.	Poor ranking could be responsible for the low CTR.
# 20	8295	REFRESH_REVIEW	STALE_HIGH_IMPRESSIONS_LOW_CTR	Meets the baseline with 3,982 impressions and position 18.8.	Position and search intent could explain the low CTR.


       days_since_last_update  impressions_90d   ctr  score  avg_position
25462                     104            16786  0.00      3           5.6
10162                     104              748  0.00      3          17.3
5716                      104             4368  0.05      3          41.2
24521                     104              890  0.00      3          19.8
1422                      104             9046  0.02      3          33.2
28482                     104             4764  0.00      3          47.1
12451                     104             2877  0.00      3          22.5
5759                      104             3828  0.05      3           6.1
18131                     104              872  0.00      3          10.8
5729                      104             2080  0.05      3           8.6
5732                      104              818  0.00      3           4.5
8306                      104             2174  0.00      3          26.2
14771                     104         

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

Eg 1: Page 5716 is a weak pick: its average position being page 41 but relatively decent number of impressions means that a refresh might not be the best approach to fixing it.

Eg 2: Page 28482 is a weak pick because its average position is 47.1. Although it has high impressions and 0 CTR, the low CTR may be explained by poor search ranking rather than outdated content.

Eg 3: Page 4489 received a score of 3 because it is more than 90 days old, has above-median impressions, and has below-median CTR. However, its average position is already relatively strong at 8.6. The low CTR may therefore be related to search intent rather than outdated content, so the refresh recommendation should be treated as directional.

In [ ]:
import os

print(os.path.exists("work/outputs/baseline_action_score.csv"))
print(os.listdir("work/outputs"))

True
['baseline_action_score.csv']


## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.